apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoriametrics:8428
      uid: PAF93674D0B4E9963
      isDefault: true
      jsonData:
        prometheusType: Prometheus
        prometheusVersion: 2.24.0