{
 "title": "FPMの情報",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "PHP-FPM 上の動的 PM を使用してプール www に到達できますか?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "phpfpm_up{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FPM が起動してからのメモリ使用量の最大値 ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "phpfpm_memory_peak{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "プロセス数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "現在のプロセスの合計数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "phpfpm_total_processes{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "現在リクエストを処理しているプロセス数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "phpfpm_active_processes{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(リクエストを待っている)現在アイドルなプロセス数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "phpfpm_idle_processes{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "同時にアクティブになったプロセスの最大数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "phpfpm_max_active_processes{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "プロセスの最大数に達したことがあるかを示します。",
   "type": "timeseries",
   "description": " ある場合、表示は 1 以上になります。 ない場合、表示は 0 になります。 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "phpfpm_max_children_reached{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "プロセスプールが最後に起動してから経過した秒数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "phpfpm_start_since{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "リクエスト数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "ある一時点でlisten キューに入ったリクエストの最大数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "phpfpm_max_listen_queue{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "許可されているlisten キューの最大サイズ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "phpfpm_listen_queue_length{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "設定した request_slowlog_timeout に到達したリクエストの合計",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "phpfpm_slow_requests{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "空きのプロセスを待っている(backlogに入っている)現在のリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "phpfpm_listen_queue{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受け入れた接続の合計数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "phpfpm_accepted_connections{job=\"php-fpm\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}