{
 "title": "php-fpm_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PHP-FPM 上の動的 PM を使用してプール www に到達できますか?",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "phpfpm_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "プロセス数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "現在のプロセスの合計数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "phpfpm_total_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "現在リクエストを処理しているプロセス数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "phpfpm_active_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(リクエストを待っている)現在アイドルなプロセス数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "phpfpm_idle_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "同時にアクティブになったプロセスの最大数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "phpfpm_max_active_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "プロセスの最大数に達したことがあるかを示します。",
   "type": "timeseries",
   "description": "ある場合、表示は 1 以上になります。 ない場合、表示は 0 になります。 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "phpfpm_max_children_reached", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "プロセスプールが最後に起動してから経過した秒数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "phpfpm_start_since", "legendFormat": "__auto" }
   ]
  },
  { "title": "リクエスト数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "ある一時点でlisten キューに入ったリクエストの最大数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "phpfpm_max_listen_queue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "許可されているlisten キューの最大サイズ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "phpfpm_listen_queue_length", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "設定した request_slowlog_timeout に到達したリクエストの合計",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "phpfpm_slow_requests", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "空きのプロセスを待っている(backlogに入っている)現在のリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "phpfpm_listen_queue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "受け入れた接続の合計数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    { "expr": "phpfpm_accepted_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "ここまでがPHP-FPMから直接とれるメトリクスと同じです.  \n<br/>\nこれ以降がphp-fpm_exporter固有のメトリクスです."
   }
  },
  { "title": "プロセス数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reading headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Reading headers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finishing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Finishing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Ending\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Getting request informations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "phpfpm_process_state{state=\"Getting request informations\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "リクエスト数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "各プロセスのリクエストの継続時間（マイクロ秒単位）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "phpfpm_process_request_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "各プロセスが処理したリクエストの数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    { "expr": "phpfpm_process_requests", "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "最後のリクエストでCPU使用量（プロセスごと）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_cpu",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "最後のリクエストが消費したメモリの最大値",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_memory",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "PHP-FPM からのスクレイピング失敗数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "targets": [
    { "expr": "phpfpm_scrape_failures", "legendFormat": "__auto" }
   ]
  }
 ]
}